#pragma config(Sensor, in1,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in2,    midLine,        sensorLineFollower)
#pragma config(Sensor, in3,    rightLine,      sensorLineFollower)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int left;
int right;
int mid;
int thresh;

task main()
{
	wait1Msec(1000);
	left=(SensorValue(leftLine));
	right=(SensorValue(rightLine));
	mid=(SensorValue(midLine));
	thresh=((((left+right)/2)+mid)/2);

while (1==1) {
		if (SensorValue(leftLine) > thresh) {
			motor (leftMotor) = 0;
			motor (rightMotor) = 40;
		}
		else if (SensorValue(midLine) > thresh){
			motor (leftMotor) = 40;
			motor (rightMotor) = 40;
		}
		else if (SensorValue(rightLine) >thresh) {
			motor (leftMotor) = 40;
			motor (rightMotor) = 0;
		}
}


}
