#pragma config(Sensor, in1,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in2,    midLine,        sensorLineFollower)
#pragma config(Sensor, in3,    rightLine,      sensorLineFollower)
#pragma config(Sensor, dgtl1,  pbtn,           sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           clawLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           clawOpen,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int thresh;
int left;
int right;
int mid;
int speed;
bool power;
bool setUpTest;
bool mode;

void turnLeft (){
	motor(rightMotor)= speed;
	motor(leftMotor)= 0;
}
void turnRight (){
	motor(rightMotor)= 0;
	motor(leftMotor)= speed;
}
void turnStraight (){
	motor(rightMotor)= speed;
	motor(leftMotor)= speed;
}
void turnStop (){
	motor (rightMotor)= 0;
	motor (leftMotor)= 0;
}
void automatic() {
	if (SensorValue(midLine) > thresh) {
		turnStraight();
	}
	else if (SensorValue(leftLine) > thresh){
		turnLeft();
	}
	else if (SensorValue(rightLine) > thresh) {
		turnRight();
	}
	else {
		turnStraight();
	}
}
void setUp() {
	if (setUpTest==false) {
		speed=(40);
		left=(SensorValue(leftLine));
		right=(SensorValue(rightLine));
		mid=(SensorValue(midLine));
		thresh=((((left+right)/2)+mid)/2);
		setUpTest=true;
	}
}
void manual () {
	if (power==true) {
		motor[rightMotor]=vexRT[Ch2];
		motor[leftMotor]=vexRT[Ch3];
		if (vexRT[Btn6U] == 1) {
			motor(clawLift)=127;
		}
		else if (vexRT[Btn6D] == 1) {
			motor(clawLift)=-127;
		}
		else {
			motor(clawLift)=0;
		}
		if (vexRT[Btn5D]==1) {
			motor(clawOpen)=-63;
		}
		else if (vexRT[Btn5U]==1) {
			motor(clawOpen)=63;
		}
		else {
			motor(clawOpen)=0;
		}
	}
	else {
		turnStop();
		motor(clawLift)=0;
	}
}

task listen() {
	while (1==1) {
		if (SensorValue(pbtn) == 1) {
			if (power==false) {
				power=true;
			}
			else {
				power=false;
			}
			wait1Msec(500);
		}
		if (vexRT[Btn8D] == 1) {
			if (mode==false) {
				mode=true;
			}
			else {
				mode=false;
			}
			wait1Msec(500);
		}
		if (vexRT[Btn8U]==1) {
			if (power==false) {
				power=true;
			}
			else {
				power=false;
			}
			wait1Msec(500);
		}
	}
	wait1Msec(10);
}
task main(){
	wait1Msec(500);
	setUp ();
	startTask(listen);
	while (1==1) {
		if (power==true){
			if (mode==false) {
				manual ();
			}
			else {
				automatic ();
			}
		}
		else {
			turnStop ();
		}
	}
	wait1Msec(10);
}
