#pragma config(Sensor, in1,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in2,    midLine,        sensorLineFollower)
#pragma config(Sensor, in3,    leftLine,       sensorLineFollower)
#pragma config(Sensor, dgtl1,  bump,           sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool started;				//power status variable, false=off true=on
int thresh;
int left;
int right;
int mid;
int speed;

void turnLeft (){
	motor(rightMotor)= speed;
	motor(leftMotor)= 0;
}
void turnRight (){
	motor(rightMotor)= 0;
	motor(leftMotor)= speed;
}
void turnStraight (){
	motor(rightMotor)= speed;
	motor(leftMotor)= speed;
}
void turnStop (){
	motor (rightMotor)= 0;
	motor (leftMotor)= 0;
}
void automatic() {
	if (SensorValue(midLine) > thresh) {
		turnStraight();
	}
	else if (SensorValue(leftLine) > thresh){
		turnLeft();
	}
	else if (SensorValue(rightLine) > thresh) {
		turnRight();
	}
	else {
		turnStraight();
	}
}
task main(){
	wait1Msec(1000);
	speed=(32);
	left=(SensorValue(leftLine));
	right=(SensorValue(rightLine));
	mid=(SensorValue(midLine));
	thresh=((((left+right)/2)+mid)/2);
	while(1==1){
		automatic ();
	}

}
