#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           clawLift,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           clawOpen,      tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void manual () {
	motor[rightMotor]=vexRT[Ch2];
	motor[leftMotor]=vexRT[Ch3];
	if (vexRT[Btn6U] == 1) {
		motor(clawLift)=127;
	}
	else if (vexRT[Btn6D] == 1) {
		motor(clawLift)=-127;
	}
	else {
		motor(clawLift)=0;
	}
	if (vexRT[Btn5D]==1) {
		motor(clawOpen)=-127;
	}
	else if (vexRT[Btn5U]==1) {
		motor(clawOpen)=0;
	}
	else {
		turnStop();
		motor(clawLift)=0;
	}
}

task main() {
	while (1==1) {
		}
	}
}
